base_url = "https://pmchp.pages.dev"
title = "PostMineClan"
description = "The page of PostMineClan"
default_language = "ja"
output_dir = "public"
compile_sass = true
build_search_index = false
taxonomies = [
    { name = "categories", feed = true, paginate_by = 10 },
    { name = "tags", fees = true, paginate_by = 10 },
]
theme = "DeepThought"
generate_feed = true
feed_filename = "atom.xml"

[markdown]
highlight_code = true
highlight_theme = "monokai"
render_emoji = true

[extra]
chart.enabled = true
mermaid.enabled = true
galleria.enabled = true

navbar_items = [
  { code = "ja",nav_items = [
  { url = "$BASE_URL/",name = "Home" },
  { url = "$BASE_URL/activity",name = "Activity" },
  { url = "$BASE_URL/posts",name = "Posts" },
  { url = "$BASE_URL/tags",name = "Tags" },
  { url = "$BASE_URL/categories", name = "Categories" },
 ]},
]


[extra.social]
twitter = "MRT1019PMC"

[extra.favicon]
favicon_16x16 = "images/Logo.jpg"
favicon_32x32 = "images/Logo.jpg"
apple_touch_icon = "images/Logo.jpg"
safari_pinned_tab = "images/Logo.jpg"
webmanifest = "images/Logo.jpg"

[extra.author]
name = "Donabe"
avatar = "images/Logo.jpg"
